# Site settings
title: Mars Luo's Note
email: lyyx_0@163.com
description: "This is Mars Luo's note book.<br/> Will record same thing interesting."
baseurl: ""
url: "http://marsluo.github.com/"
username: MarsLuo

# Build settings
markdown: kramdown
permalink: pretty
paginate: 8
gems: [jekyll-paginate]
